#!/bin/bash
#Graphical version of Wizard using zenity (to use gfxwizard you will need to have zenity and wizard installed
#by Demiurgos Software
#https://github.com/demiurgosoft/wizard

#install a file with wizard with a graphical interface
#programmed by Demiurgos
file=`zenity --file-selection`
dir=${file%/*}
name=${file##*/}
cd $dir
zenity --info --text=`gksudo wizard $name`
