#!/bin/bash
#Wizard Allow you to install and remove binary files and scripts in yout $DIRECTORY/ folder
#by @angrykoala
#https://github.com/angrykoala/wizard

DIRECTORY="/usr/local/bin"

if [ ! -d "$DIRECTORY" ]; then
	mkdir $DIRECTORY
fi


if [ $# -eq 0 ]
	then echo "No Arguments Provided"
fi
if [ $# -eq 1 ] #Only 1 argument
	then
	if [ "$1" == "-help" ] #if the argument is -help show manual
		then
		echo "                Wizard 0.2 by @angrykoala"
		echo "This Program allow you to install and remove programs in $DIRECTORY/"
		echo "Syntaxis: wizard [Option] [files]"
		echo "Wizard allow the next options"
		echo "   -install (not needed), install files in $DIRECTORY/"
		echo "   -list list all your files in $DIRECTORY/ directory"
		echo "   -remove [files] remove te given files from bin directory"
		echo "   -help show this dialog"
		echo "   -removeall remove ALL your files in bin directory"
		echo "   -copy copy files into your actual directory"
		echo "Keep in mind that the folder is not exclusive from wizard, and it may affect other programs"
	elif [ "$1" == "-list" ] #Show all installed Bins if the argument is -list
		then
		ls $DIRECTORY
	elif [ "$1" == "-removeall" ] #remove all installed Bins
		then
		echo "-removeall will remove all your files in $DIRECTORY/"
		read -p "Are you sure? (Y/N) " -n 1 -r
		echo    # (optional) move to a new line
		if [[ $REPLY =~ ^[Yy]$ ]]
			then
			echo "removing all Programs"
			ls $DIRECTORY
			sudo rm $DIRECTORY/*
		fi
	elif [ "$1" == "-remove" ] # Error, needed more arguments
		then echo "[-remove] option needs more arguments"
	elif [ "$1" == "-copy" ] #Error
		then echo "[-copy] option needs more arguments"
	elif [ "$1" == "-install" ] #Error
		then echo "[-install] option needs more arguments"
	else                 #if the only argument is not -help or -list, do installation
		echo "Installing "$1
		sudo cp $1 $DIRECTORY/$1
		sudo chmod a+rwx $DIRECTORY/$1
	fi

elif [ $# -gt 1 ] #More than 1 argument
then
	if [ "$1" == "-remove" ]
		then
		shift #skips first argument
		echo "Removing "$@
		for var in "$@"
		do
   			sudo rm $DIRECTORY/$var
		done
	elif [ "$1" == "-copy" ]
		then
		shift #skips -copy argument
		echo "Copying "$@
		for var in "$@"
		do
   			cp $DIRECTORY/$var $var
		done

	else
		if [ "$1" == "-install" ]
			then
			shift #skips -install argument
		fi #begins normal instalation (after skipping -install or without it)
	echo "Installing "$@
	for var in "$@"
	do
  		sudo cp $var $DIRECTORY/$var
  		sudo chmod a+rwx $DIRECTORY/$var
	done
	fi
fi
